In [2]:
#Importing necessary Modules
# Author : Ketul Shah & Subham Malaviya
import matplotlib
matplotlib.use('TkAgg')
import matplotlib.pyplot as plt
import numpy as np
import matplotlib.image as mpimg
from numpy.linalg import inv
from numpy.linalg import pinv

In [16]:
no_points = 8
img1 = plt.imread('img1.jpg') # Reading image1 from source
img2 = plt.imread('img2.jpg') # Reading image2 from source
plt.figure(figsize=(10,10))
plt.subplot(121)
plt.title('Image 1')
plt.gray()
imgplot1 = plt.imshow(img1)
plt.subplot(122)
plt.title('Image 2')
imgplot2 = plt.imshow(img2)
print("Please click 4 points look similar in two images (from Image1)")
x1 = np.zeros(shape=(int(no_points/2),2))
x = plt.ginput(int(no_points/2))
for i in range(int(no_points/2)):
    x1[i][0] = x[i][0]
    x1[i][1] = x[i][1]
x2 = np.zeros(shape=(int(no_points/2),2))
print("Now Please click 4 point looks similar in two images (from Image2)")
x = plt.ginput(int(no_points/2))
for i in range(int(no_points/2)):
    x2[i][0] = x[i][0]
    x2[i][1] = x[i][1]
#print("clicked", x)
matX = np.zeros(shape=(int(no_points/2),int(no_points/2)))
for i in range(int(no_points/2)):
    matX[0][i] = x1[i][0]
for i in range(int(no_points/2)):
    matX[1][i] = x1[i][1]
for i in range(int(no_points/2)):
    matX[2][i] = x1[i][1] * x1[i][0]
for i in range(int(no_points/2)):
    matX[3][i] = 1
#print(matX)
matX_inv = pinv(matX)
coeff_mat = np.matmul(np.transpose(x2),matX_inv)
#print(x1)
#print(matX_inv.shape)
print(coeff_mat)
plt.close()
#plt.show()

Please click 4 points look similar in two images (from Image1)


/usr/local/lib/python3.6/site-packages/matplotlib/backend_bases.py:2453: MatplotlibDeprecationWarning: Using default event loop until function specific to this GUI is implemented
  warnings.warn(str, mplDeprecation)


Now Please click 4 point looks similar in two images (from Image2)
[[  1.10915694e+00   7.31711608e-01  -6.83533812e-04  -1.57541620e+02]
 [ -3.50978459e-01   1.07103731e+00  -3.97172609e-04   1.23661848e+02]]


In [20]:
M = img1.shape[0] 
N = img1.shape[1] 
img3 = 
count = 0
print(coeff_mat)
for i in range(int(M)):
    for j in range(int(N)):
        x1 = int(coeff_mat[0][0]*i + coeff_mat[0][1]*j + coeff_mat[0][2]*i*j + coeff_mat[0][3]) 
        y1 = int(coeff_mat[1][0]*i + coeff_mat[1][1]*j + coeff_mat[1][2]*i*j + coeff_mat[1][3])
        if(x1 <= M  and y1 <=N and x1 >= 0 and y1 >=0):
            count += 1
            img3[x1][y1] = img1[i][j]
plt.imshow(img3)
print(count)
plt.show()

[[  1.10915694e+00   7.31711608e-01  -6.83533812e-04  -1.57541620e+02]
 [ -3.50978459e-01   1.07103731e+00  -3.97172609e-04   1.23661848e+02]]


IndexError: index 778 is out of bounds for axis 0 with size 778